### ISSUE TITLE
Document the staggering scheme

### ISSUE THREAD

**Issue by tobson** [nbia-astro/skeletor#105]

**Comment by tobson** [comment]
@tberlok A condensed version of the dedicated set of notes you wrote on this should be in the code's documentation (i.e. in `pp-hybrid`).

**Comment by tberlok** [comment]
I have now pushed something to the branch 'interlaced' in the pp-hybrid repo.

**Comment by tobson** [comment]
Excellent, thanks. I moved this repository over to GitHub: https://github.com/nbia-astro/pp-hybrid

**Comment by tberlok** [comment]
I've been added to the google group but I am not sure I have been invited to the github repo.

**Comment by tobson** [comment]
Oh, right! One sec...

**Comment by tberlok** [comment]
Got it! And created a pull request.

**Comment by tobson** [comment]
Merged.

**Comment by tobson** [comment]
Fixed in nbia-astro/pp-hybrid@12da4d4e597cc0d9c01019e018e66d70dbfbb38b. Closing...
