### ISSUE TITLE
Get all examples working with the current version of the code

### ISSUE THREAD

**Issue by tobson** [nbia-astro/skeletor#119]
The following examples are currently broken:
1. ~~shearing_epicycle~~
2. ~~sheared_burgers_widget~~
3. ~~pizza2d~~
4. ~~nonlinear_shearing_wave~~
5. ~~many_epicycles~~ (not fixed by removed instead)

**Comment by tberlok** [comment]
1 has been turned into a test on master.
2 has been fixed.

**Comment by tberlok** [comment]
3 is fixed.

**Comment by tberlok** [comment]
4 is fixed.

**Comment by tberlok** [comment]
5 has been deleted.

I think it is easier to create this again from scratch and the nonlinear shearing wave example is superior in any case.
