### ISSUE TITLE
Lx hardcoded to 1 in DensityPerturbation class?

### ISSUE THREAD

**Issue by tobson** [nbia-astro/skeletor#123]
@tberlok [These](https://github.com/nbia-astro/skeletor/blob/cfec260199bcae63c0e0e6b1b0a10aa7e7a5da66/skeletor/initial_condition.py#L94-L96) lines of code appear to me to be only correct if `Lx=1`. Or is there something about `find_cdf()` that I don't understand?

**Comment by tberlok** [comment]
This is just bad very bad naming convention which I also find confusing now. The variable Ux is not the x positions but an array uniformly distributed numbers used to calculate the values of the x-positions.

I will push a fix in a minute.

**Comment by tobson** [comment]
Also, I understand that Ux is an array of positions, but shouldn't it go 0
to Lx? Uy seems to do that (on one processor at least).

**Comment by tobson** [comment]
I see, so Uy was the actual y-coordinate in physical units but Ux was an
array going from 0 to 1? That is confusing...

**Comment by tobson** [comment]
How about we rename Uy to y1? In analogy with how things are named in the
InitialCondition class?

**Comment by tberlok** [comment]
Yes, very confusing indeed. Your idea for renaming is obviously the correct way. I will fix it immediately.
