### ISSUE TITLE
Make a omega vs k plot for ion-acoustic waves

### ISSUE THREAD

**Issue by tberlok** [nbia-astro/skeletor#13]
Make a omega vs k plot for ion-acoustic waves. This was a great test of the ion-acoustic waves in the 1D python code and the ppcode (which did not do as well). When this works and matches theory, merge the branch dispersion_solvers into master.

**Comment by tberlok** [comment]
This issue is on hold until we have a less  unstable cold ionacoustic wave, see #15. Furthermore, the dispersion relation I have derived is only valid for finite differences, so we need to extend it to ffts.

**Comment by tberlok** [comment]
Given that I seem to have found the issues with #15 and #16 I can now run the ion-acoustic wave experiment to produce a omega vs k plot. Notice that the theoretical curve is not expected to match since we have not derived the curve for ffts but only for finite differences. This plot was made by only considering wavenumbers up to kmax/3, see #15.
[omega_vs_k.pdf](https://github.com/nbia-astro/skeletor/files/509777/omega_vs_k.pdf)

**Comment by tberlok** [comment]
This issue has been solved but the result has not been merged into master yet. Nevertheless I am closing this issue.

**Comment by tobson** [comment]
Let's close this once the branch in question has been merged.

**Comment by tobson** [comment]
Let's close this once the branch in question has been merged.

**Comment by tberlok** [comment]
This was fixed in d1b07c0a5269b2ffc29ad083dcbb06db478dcb65.

See also:
![figure_2](https://cloud.githubusercontent.com/assets/10655136/23579715/809182c0-00f3-11e7-81dc-d9753f5fa4c5.png)
