### ISSUE TITLE
Unify field classes

### ISSUE THREAD

**Issue by tobson** [nbia-astro/skeletor#150]
Right now there's `Field` and `ShearingField`. The former _only_ works with `Manifold` and the latter _only_ works with `ShearingManifold`. This is not desirable because we likely end up with a lot of classes that come in a regular version and a shearing sheet version.

Instead there should be just one field class that just does the right thing depending on which manifold is used when a field is constructed. This will require the manifold to know about boundary conditions.

**Comment by tberlok** [comment]
The field classes have been unified.
