### ISSUE TITLE
Weird dimple in density maxima when exciting with sinusoidal velocity perturbation

### ISSUE THREAD

**Issue by tberlok** [nbia-astro/skeletor#16]
Currently uncertain whether this is a bug in the code or a problem with initialization.

**Comment by tberlok** [comment]
**I have found the source of this problem:**

When initializing the particles with a quiet start some of the particles will be located directly on grid points. I think this gives numerical problems when determining the grid index (x = <int> x). For a test with nx = 64 and kx = 2 2pi/nx the dimples appear at x = 0, 16, 32, 48. These are also the locations where particles are located directly on the grid point. I believe this is not a coincidence.

**I can make the dimples disappear by adding an irrational number x = x + sqrt(2) and then apply the periodic boundary conditions such that no particles coincide with grid points.**

**Comment by tberlok** [comment]
The dimples reappear if one runs the simulation for a little while...

@tobson: Do you think think we will need to use the integer + fractional position in the box model instead? And what about single vs double precision?

**Comment by tberlok** [comment]
Okay, as I suggested above, the issue is related to the precision used. I have converted all the float to doubles (on my laptop so far) and the dimples disappeared for good. My understanding is that the ppcode has often been used with single precision which might be why they found the integer + fractional position in the box model to better. I suggest we continue with our current setup but with double precision.

**Comment by tberlok** [comment]
I have only converted the reals to double precision in 55a1aea5c. Maybe we should also convert the complex number to double precision?

**Comment by tberlok** [comment]
Okay, so it does not compile with operators.pyx which have been merged into the master branch after the branch I was working on diverged. The issue is the one found here: http://stackoverflow.com/questions/30054019/complex-numbers-in-cython

I can get it to compile by manually fixing the .c file. I'll try to get it to work directly too.

**Comment by tobson** [comment]
@tberlok Do you think that in order get rid of the dimple, it might suffice to use double precision for the particle positions?

**Comment by tberlok** [comment]
Yes, I think that is true. If not my explanation for the dimple is wrong.

**Comment by tberlok** [comment]
This issue was solved by switching to double precision in particle positions, see #21.
