### ISSUE TITLE
Improve prepare() method in predictor-corrector

### ISSUE THREAD

**Issue by tberlok** [nbia-astro/skeletor#84]
If one thread converges before the others then that causes problems for the MPI.

**Comment by tobson** [comment]
This is only an issue in `prepare()`, right?

**Comment by tobson** [comment]
Now the previous error is back, see https://travis-ci.com/nbia-astro/skeletor/builds/41208234

Do you know why the following assertion might fail?
```python
assert all(self["y"][:self.np] >= self.manifold.edges[0])
```

**Comment by tberlok** [comment]
Right.

**Comment by tberlok** [comment]
No, I don't understand it... I will take a look tomorrow (unless you find
it first, of course).

**Comment by tobson** [comment]
This issue is fixed by a61d2ee. Closing...
