### ISSUE TITLE
Change default domain size

### ISSUE THREAD

**Issue by tobson** [nbia-astro/skeletor#95]
Now that we're not constrained anymore by the choice of units the particle positions are measured in, I suggest we set `Lx=Ly=1` rather than `Lx=nx` and `Ly=ny` by default. I cannot think of a good reason why one would ever choose the latter.

**Comment by tberlok** [comment]
I agree with this although it will require a few changes to the tests.

**Comment by tberlok** [comment]
These are the tests we need to modify. We can write comments below with the numbers that we are working on/have modified.

1. ~~test_EcrossBdrift_along_x.py~~
2. ~~test_EcrossBdrift_along_y.py~~
3. ~~test_burgers.py~~
4. ~~test_circular.py~~
5. ~~test_copy_guards_with_shear.py~~
6. ~~test_deposit.py~~
7. ~~test_extended_grid.py~~
8. ~~test_fastwave.py~~
9. ~~test_gyromotion.py~~
10. ~~test_ionacoustic.py~~
11. ~~test_plasmafrequency.py~~
12. ~~test_sheared_burgers.py~~
13. ~~test_sheared_disturbance.py~~
14. ~~test_shearing_epicycle_standard_coordinates.py~~
15. ~~test_skeletor.py~~
16. ~~test_translate.py~~
17. ~~test_twostream.py~~

**Comment by tobson** [comment]
15 is done.

**Comment by tobson** [comment]
6 and 10 are done.

**Comment by tobson** [comment]
3 is working now. The reason it wasn't before was that the standalong "drift()" method wasn't aware of non-unit grid spacing.

**Comment by tobson** [comment]
4 and 8 have non-unit grid spacing already.

**Comment by tobson** [comment]
11 is done.

**Comment by tobson** [comment]
12 is done.

**Comment by tobson** [comment]
13 is done.

**Comment by tobson** [comment]
13 isn't actually working with more than one MPI process.

**Comment by tobson** [comment]
13 is working again.

**Comment by tobson** [comment]
1 and 2 are taken care of.

**Comment by tobson** [comment]
5 is working.

**Comment by tobson** [comment]
7 is done.

**Comment by tobson** [comment]
9 is done.

**Comment by tobson** [comment]
16 is working too now.

**Comment by tobson** [comment]
@tberlok Please take care of the last two remaining ones. In the two-stream instability test, make sure the parameters are such that the wavelength of the fastest growing mode is equal to the box size.

**Comment by tberlok** [comment]
14 and 17 are done.

**Comment by tberlok** [comment]
Everything should be working now but some things will probably break when we merge in #121.
